"""Pydantic models used across all functions."""
from typing import Optional
from pydantic import BaseModel, Field


class CleaningConfig(BaseModel):
    """Loaded from bhp_config.json. Contains schema, taxonomy, vendors, distributions."""
    schema: list[dict] = Field(default_factory=list)
    category_taxonomy: dict = Field(default_factory=dict)
    top_20_suppliers: list[dict] = Field(default_factory=list)
    units: list[str] = Field(default_factory=list)
    payment_terms: list[str] = Field(default_factory=list)
    date_range: Optional[dict] = None
    valid_currencies: list[str] = Field(default_factory=lambda: ["AUD", "USD", "CLP"])


class ColumnProfile(BaseModel):
    """Profile for a single column."""
    name: str
    dtype_detected: str
    null_count: int
    null_rate: float
    unique_count: int
    cardinality: float
    sample_values: list[str] = Field(default_factory=list)
    anomaly_flags: list[str] = Field(default_factory=list)
    distribution_summary: dict = Field(default_factory=dict)


class ProfileResult(BaseModel):
    """Output of profile_data function."""
    total_rows: int
    total_columns: int
    columns: list[ColumnProfile]
    duplicate_count: int
    near_duplicate_count: int
    encoding_issues: int
    overall_quality_score: float


class CleaningStrategy(BaseModel):
    """Output of Stage 2 strategy planning (generated by Copilot Studio LLM)."""
    deterministic_fields: list[str] = Field(default_factory=list)
    llm_fields: list[str] = Field(default_factory=list)
    priority_order: list[str] = Field(default_factory=list)
    estimated_llm_records: int = 0
    notes: str = ""


class FieldChange(BaseModel):
    """Tracks a single field modification."""
    field: str
    original_value: Optional[str] = None
    new_value: Optional[str] = None
    method: str
    confidence: float
    agent: str


class CleanedRecord(BaseModel):
    """A single cleaned record with provenance."""
    record_id: str
    fields: dict
    changes: list[FieldChange] = Field(default_factory=list)
    confidence: float
    needs_review: bool


class ValidationResult(BaseModel):
    """Output of validate_output function."""
    is_valid: bool
    total_records: int
    schema_errors: list[dict] = Field(default_factory=list)
    consistency_issues: list[dict] = Field(default_factory=list)
    outliers: list[dict] = Field(default_factory=list)
    stats: dict = Field(default_factory=dict)


class FlaggedRecord(BaseModel):
    """A record that needs LLM reasoning or human review."""
    record_id: str
    original_row: dict
    partially_cleaned: dict
    flagged_fields: list[str]
    vendor_candidates: Optional[list[dict]] = None
    suggested_category: Optional[dict] = None
    reason: str
